# Generated by Django 2.0.7 on 2018-11-05 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobinagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_emendas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de emendas')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Bobinagem')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('num_bobinagem', models.PositiveIntegerField(verbose_name='Bobinagem nº')),
                ('comp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento Final')),
                ('tiponwsup', models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici')], default='', max_length=40, null=True, verbose_name='Tipo Nonwoven Superior')),
                ('tiponwinf', models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici')], default='', max_length=40, null=True, verbose_name='Tipo Nonwoven Inferior')),
                ('estado', models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB'), ('IND', 'IND')], default='LAB', max_length=3, verbose_name='Estado')),
                ('lotenwsup', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Superior')),
                ('lotenwinf', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Inferior')),
                ('nwsup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Superior')),
                ('nwinf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Inferior')),
                ('comp_par', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Comprimento Emenda')),
                ('comp_cli', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento Cliente')),
                ('desper', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desperdício')),
                ('diam', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diametro')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área')),
                ('inico', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('fim', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('duracao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duração')),
                ('obs', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Observações')),
                ('area_g', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Good')),
                ('area_dm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área DM')),
                ('area_r', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área R')),
                ('area_ind', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área Ind')),
                ('area_ba', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Área BA')),
            ],
            options={
                'verbose_name_plural': 'Bobinagens',
                'ordering': ['-data', '-fim', '-nome'],
            },
        ),
        migrations.CreateModel(
            name='Bobine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_actual', models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='Comprimento actual')),
                ('nome', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Bobine')),
                ('posicao_palete', models.PositiveIntegerField(default=0, verbose_name='Posição')),
                ('estado', models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB'), ('IND', 'IND'), ('HOLD', 'HOLD')], default='G', max_length=4, verbose_name='Estado')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área bobine')),
                ('con', models.BooleanField(default=False, verbose_name='Cónica')),
                ('descen', models.BooleanField(default=False, verbose_name='Descentrada')),
                ('presa', models.BooleanField(default=False, verbose_name='Presa')),
                ('diam_insuf', models.BooleanField(default=False, verbose_name='Diâmetro insuficiente')),
                ('furos', models.BooleanField(default=False, verbose_name='Furos')),
                ('esp', models.BooleanField(default=False, verbose_name='Gramagem')),
                ('troca_nw', models.BooleanField(default=False, verbose_name='Troca NW')),
                ('outros', models.BooleanField(default=False, verbose_name='Outros')),
                ('buraco', models.BooleanField(default=False, verbose_name='Buracos')),
                ('obs', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Observações')),
                ('bobinagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Bobinagem', verbose_name='Bobinagem')),
            ],
            options={
                'verbose_name_plural': 'Bobines',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cod', models.PositiveIntegerField(unique=True, verbose_name='Código de cliente')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome')),
                ('limsup', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Superior')),
                ('liminf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Inferior')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-timestamp', '-nome'],
            },
        ),
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_emenda', models.IntegerField(blank=True, default=0, null=True, verbose_name='Bobine nº')),
                ('emenda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Emenda metros')),
                ('metros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Metros gastos')),
                ('bobinagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.Bobinagem', verbose_name='Bobinagem')),
                ('bobine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobine', verbose_name='Bobine')),
            ],
        ),
        migrations.CreateModel(
            name='Largura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bobine', models.PositiveIntegerField(verbose_name='Bobine nº')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Larguras',
                'ordering': ['perfil'],
            },
        ),
        migrations.CreateModel(
            name='Palete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_pal', models.DateField(default=datetime.date.today)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Palete')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Palete nº')),
                ('estado', models.CharField(choices=[('G', 'G'), ('DM', 'DM')], default='G', max_length=2, verbose_name='Estado')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área palete')),
                ('comp_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento palete')),
                ('lote', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nº Lote')),
                ('num_bobines', models.IntegerField(verbose_name='Bobines total')),
                ('num_bobines_act', models.IntegerField(default=0)),
                ('largura_bobines', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura das bobines')),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Diâmetro das bobines')),
                ('core_bobines', models.CharField(choices=[('3', '3'), ('6', '6')], max_length=1, verbose_name='Core das bobines')),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto')),
                ('peso_palete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso palete')),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso liqudo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Cliente', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Paletes',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Perfil')),
                ('produto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Produto')),
                ('retrabalho', models.BooleanField(default=False, verbose_name='Retrabalho')),
                ('num_bobines', models.PositiveIntegerField(verbose_name='Número de bobines')),
                ('largura_bobinagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largura da bobinagem')),
                ('core', models.CharField(choices=[('3', '3'), ('6', '6')], max_length=1, verbose_name='Core')),
                ('gramagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gramagem')),
                ('espessura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura')),
                ('densidade_mp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidade da matéria prima')),
                ('velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Velocidade')),
                ('producao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Produção')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Perfis',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='largura',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Perfil', verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='largura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Largura', verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='palete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.Palete'),
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Perfil', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
