# Generated by Django 2.0.7 on 2018-11-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='retrabalhada',
            field=models.BooleanField(default=False, verbose_name='Retrabalhada'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='data_pal',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Palete'),
        ),
    ]
