# Generated by Django 2.0.7 on 2018-11-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20181106_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palete',
            options={'ordering': ['-num'], 'verbose_name_plural': 'Paletes'},
        ),
    ]
