# Generated by Django 2.0.7 on 2018-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_auto_20181108_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 1'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine10',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 10'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine11',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 11'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine12',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 12'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine13',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 13'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine14',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 14'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine15',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 15'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine16',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 16'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine17',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 17'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine18',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 18'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine19',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 19'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 2'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine20',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 20'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine21',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 21'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine22',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 22'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine23',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 23'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine24',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 24'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine25',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 25'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine26',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 26'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine27',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 27'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine28',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 28'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine29',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 29'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 3'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine30',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 30'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine31',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 31'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine32',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 32'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine33',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 33'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine34',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 34'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine35',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 35'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine36',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 36'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine37',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 37'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine38',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 38'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine39',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 39'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 4'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine40',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 40'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine41',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 41'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine42',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 42'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine43',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 43'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine44',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 44'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine45',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 45'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine46',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 46'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine47',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 47'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine48',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 48'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine49',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 49'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 5'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine50',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 50'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine51',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 51'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine52',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 52'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine53',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 53'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine54',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 54'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine55',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 55'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine56',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 56'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine57',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 57'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine58',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 58'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine59',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 59'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 6'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine60',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 60'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 7'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 8'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='bobine9',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bobine nº 9'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='diam_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro máximo'),
        ),
        migrations.AlterField(
            model_name='etiquetapalete',
            name='diam_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro minimo'),
        ),
    ]
