# Generated by Django 2.0.7 on 2018-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_auto_20181108_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área'),
        ),
    ]
