# Generated by Django 2.0.7 on 2018-11-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_auto_20181119_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobine',
            name='comp_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comprimento actual'),
        ),
    ]
