# Generated by Django 2.0.7 on 2018-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_auto_20181120_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobine',
            name='comp_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Comprimento actual'),
        ),
    ]
