# Generated by Django 2.1.3 on 2018-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_auto_20181210_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='recycle',
            field=models.BooleanField(default=False, verbose_name='Reciclada'),
        ),
    ]
