# Generated by Django 2.1.3 on 2019-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_bobine_recycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palete',
            options={'ordering': ['-data_pal', '-num'], 'verbose_name_plural': 'Paletes'},
        ),
        migrations.AddField(
            model_name='largura',
            name='designacao_prod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Designação produto'),
        ),
        migrations.AlterField(
            model_name='largura',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
