# Generated by Django 2.1.3 on 2019-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_auto_20190307_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB'), ('IND', 'IND'), ('HOLD', 'HOLD')], default='LAB', max_length=4, verbose_name='Estado'),
        ),
    ]
