# Generated by Django 2.1.3 on 2019-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0018_auto_20190321_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='num_cargas_sctual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='eef',
            field=models.CharField(max_length=17, unique=True, verbose_name='Encomenda'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='prf',
            field=models.CharField(max_length=15, unique=True, verbose_name='Proforma'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='peso_palete',
            field=models.CharField(blank=True, choices=[('8', '8 Kg'), ('13', '13 Kg')], max_length=5, null=True, verbose_name='Peso palete'),
        ),
    ]
