# Generated by Django 2.1.3 on 2019-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_auto_20190329_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='metros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Metros lineares'),
        ),
    ]
