# Generated by Django 2.1.3 on 2019-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0022_auto_20190401_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carga',
            options={'ordering': ['-carga', '-data'], 'verbose_name_plural': 'Cargas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='abv',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Abreviatura'),
        ),
    ]
