# Generated by Django 2.1.3 on 2019-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_auto_20190401_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palete',
            name='core_bobines',
            field=models.CharField(choices=[('3', '3'), ('6', '6')], default='3', max_length=1, verbose_name='Core das bobines'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='largura_bobines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largura das bobines'),
        ),
    ]
