# Generated by Django 2.1.3 on 2019-04-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0024_auto_20190403_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palete_nome', models.CharField(max_length=200, verbose_name='Palete nome')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('largura_bobine', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largura')),
                ('diam_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro minimo')),
                ('diam_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro máximo')),
                ('cod_cliente', models.IntegerField(verbose_name='Cód. Cliente')),
                ('cod_cliente_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cód. Cliente do Cliente')),
                ('pais', models.CharField(default='Portugal', max_length=200, verbose_name='Produido em:')),
                ('poroduzido_por', models.CharField(default='Elastictek', max_length=200, verbose_name='Produido por:')),
                ('core', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Core')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Área')),
                ('comp', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Comprimento')),
                ('prf', models.CharField(max_length=200, verbose_name='Proforma')),
                ('num_bobines', models.IntegerField(verbose_name='Nº de bobines')),
                ('palete_num', models.IntegerField(verbose_name='Paleten nº')),
                ('palete_total', models.IntegerField(verbose_name='Paleten total')),
                ('peso_liquido', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Líquido')),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Bruto')),
                ('data_prod', models.DateField(verbose_name='Data de produção')),
                ('data_validade', models.DateField(verbose_name='Validade')),
                ('gsm', models.IntegerField(verbose_name='Gramagem')),
                ('palete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Palete', verbose_name='Palete')),
            ],
        ),
        migrations.AddField(
            model_name='largura',
            name='gsm',
            field=models.CharField(blank=True, choices=[('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm')], max_length=7, null=True, verbose_name='Gramagem'),
        ),
    ]
