# Generated by Django 2.2 on 2019-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0028_bobine_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='gtin',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='cod',
            field=models.CharField(max_length=18, unique=True, verbose_name='Cód. Artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(default='Produto final', max_length=50, verbose_name='Tipo'),
        ),
    ]
