# Generated by Django 2.2 on 2019-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0029_auto_20190502_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='core',
            field=models.CharField(choices=[('3', '3'), ('6', '6')], default='', max_length=1, verbose_name='Core'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='diam_ref',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diametro de referência'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='formu',
            field=models.CharField(choices=[('HE', 'HE'), ('HT', 'HT')], default='', max_length=10, verbose_name='Formulação'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='gsm',
            field=models.CharField(blank=True, choices=[('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm')], max_length=1, null=True, verbose_name='Gramagem'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='lar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='nw1',
            field=models.CharField(default='', max_length=10, verbose_name='NW1'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='nw2',
            field=models.CharField(default='', max_length=10, verbose_name='NW2'),
        ),
    ]
