# Generated by Django 2.2 on 2019-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0030_auto_20190502_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='nw2',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='NW2'),
        ),
    ]
