# Generated by Django 2.2 on 2019-05-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0032_auto_20190502_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largura',
            name='artigo',
        ),
        migrations.AddField(
            model_name='bobine',
            name='artigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Artigo', verbose_name='Artigo'),
        ),
    ]
