# Generated by Django 2.2.7 on 2019-12-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0037_perfil_obsoleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['estado', '-data', '-eef'], 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AddField(
            model_name='bobine',
            name='l_real',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largura Real'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='nok',
            field=models.BooleanField(default=False, verbose_name='Largura NOK'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='cont',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='control',
            field=models.PositiveIntegerField(default=0, verbose_name='Variável de controlo'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='gtin',
            field=models.CharField(default='', max_length=14, verbose_name='GTIN'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='impressora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='sscc',
            field=models.CharField(default='', max_length=18, verbose_name='SSCC'),
        ),
        migrations.AddField(
            model_name='etiquetapalete',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetapalete',
            name='impressora',
            field=models.CharField(blank=True, choices=[('Bobinadora_CAB_A4_200', 'BOBINADORA'), ('DM12_CAB_A4_200', 'DM12')], max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetapalete',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
        migrations.AddField(
            model_name='etiquetaretrabalho',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetaretrabalho',
            name='impressora',
            field=models.CharField(blank=True, choices=[('Bobinadora_CAB_A4_200', 'BOBINADORA'), ('DM12_CAB_A4_200', 'DM12')], max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetaretrabalho',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='core_original',
            field=models.CharField(blank=True, choices=[('3', '3'), ('6', '6')], max_length=1, null=True, verbose_name='Core'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='largura_original',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura da bobinagem'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='gsm',
            field=models.CharField(blank=True, choices=[('105', '105 gsm'), ('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm'), ('57', '57 gsm'), ('50', '50 gsm'), ('48', '48 gsm')], max_length=10, null=True, verbose_name='Gramagem'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='produto',
            field=models.CharField(choices=[('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HT', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HT'), ('NONWOVEN ELASTIC BANDS ELA-ACE 95 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 95 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL'), ('SIDE PANEL ELA-ACE 100 HE', 'SIDE PANEL ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO'), ('NONWOVEN ELASTIC BANDS ELA-ACE 105 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 105 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)'), ('FRONTAL TAPE 48', 'FRONTAL TAPE 48'), ('CAR PROTECTION SHEET 57', 'CAR PROTECTION SHEET 57'), ('ELASTIC FILM', 'ELASTIC FILM')], default='', max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='comp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Comprimento Final'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='tiponwinf',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS', 'ALBIS'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV')], default='', max_length=40, null=True, verbose_name='Tipo Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='tiponwsup',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS', 'ALBIS'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV')], default='', max_length=40, null=True, verbose_name='Tipo Nonwoven Superior'),
        ),
        migrations.AlterField(
            model_name='etiquetafinal',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=15, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='largura',
            name='designacao_prod',
            field=models.CharField(choices=[('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HT', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HT'), ('NONWOVEN ELASTIC BANDS ELA-ACE 95 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 95 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL'), ('SIDE PANEL ELA-ACE 100 HE', 'SIDE PANEL ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO'), ('NONWOVEN ELASTIC BANDS ELA-ACE 105 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 105 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)'), ('FRONTAL TAPE 48', 'FRONTAL TAPE 48'), ('CAR PROTECTION SHEET 57', 'CAR PROTECTION SHEET 57'), ('ELASTIC FILM', 'ELASTIC FILM')], default='', max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='largura',
            name='gsm',
            field=models.CharField(blank=True, choices=[('105', '105 gsm'), ('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm'), ('57', '57 gsm'), ('50', '50 gsm'), ('48', '48 gsm')], max_length=7, null=True, verbose_name='Gramagem'),
        ),
        migrations.AlterField(
            model_name='largura',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='palete',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=11, verbose_name='Área palete'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='peso_palete',
            field=models.CharField(blank=True, choices=[('0', '0 Kg'), ('8', '8 Kg'), ('13', '13 Kg')], max_length=5, null=True, verbose_name='Peso palete'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='gramagem',
            field=models.CharField(blank=True, choices=[('105', '105 gsm'), ('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm'), ('57', '57 gsm'), ('50', '50 gsm'), ('48', '48 gsm')], max_length=10, null=True, verbose_name='Gramagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='largura_bobinagem',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura da bobinagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='produto',
            field=models.CharField(choices=[('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HT', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HT'), ('NONWOVEN ELASTIC BANDS ELA-ACE 95 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 95 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 90 HT HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 95 HE HL'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE HL'), ('SIDE PANEL ELA-ACE 100 HE', 'SIDE PANEL ELA-ACE 100 HE'), ('NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO', 'NONWOVEN ELASTIC BANDS ELA-SPUN 100 HE BICO'), ('NONWOVEN ELASTIC BANDS ELA-ACE 105 HE', 'NONWOVEN ELASTIC BANDS ELA-ACE 105 HE'), ('NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)', 'NONWOVEN ELASTIC BANDS ELA-ACE 100 HE(D)'), ('FRONTAL TAPE 48', 'FRONTAL TAPE 48'), ('CAR PROTECTION SHEET 57', 'CAR PROTECTION SHEET 57'), ('ELASTIC FILM', 'ELASTIC FILM')], default='', max_length=100, verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='Nonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('designacao_fornecedor', models.CharField(max_length=200, unique=True, verbose_name='Designação do Fornecedor')),
                ('comp_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento total')),
                ('comp_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento actual')),
                ('largura', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('vazio', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Fornecedor', verbose_name='Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Nonwovens',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoNonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posicao', models.CharField(choices=[('SUP', 'Superior'), ('INF', 'Inferior')], max_length=10, verbose_name='Posição (Sup/Inf)')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('bobinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobinagem', verbose_name='Bobinagem')),
                ('nonwoven', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Nonwoven', verbose_name='Nonwoven')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Consumos de Nonwoven',
                'ordering': ['-timestamp'],
            },
        ),
    ]
