# Generated by Django 2.2 on 2019-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0038_auto_20190507_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetafinal',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='cont',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='control',
            field=models.PositiveIntegerField(default=0, verbose_name='Variável de controlo'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='gtin',
            field=models.CharField(default='', max_length=14, verbose_name='GTIN'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='sscc',
            field=models.CharField(default='', max_length=18, verbose_name='SSCC'),
        ),
    ]
