# Generated by Django 2.2 on 2019-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0039_auto_20190507_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetafinal',
            name='cont',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Contador'),
        ),
        migrations.AlterField(
            model_name='etiquetafinal',
            name='sscc',
            field=models.CharField(default='', max_length=18, unique=True, verbose_name='SSCC'),
        ),
    ]
