# Generated by Django 2.2 on 2019-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0040_auto_20190507_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetafinal',
            name='sscc',
            field=models.CharField(default='', max_length=18, verbose_name='SSCC'),
        ),
    ]
