# Generated by Django 2.2.1 on 2019-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0044_auto_20190705_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobine',
            name='m_real',
        ),
        migrations.AddField(
            model_name='bobine',
            name='l_real',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largura Real'),
        ),
    ]
