# Generated by Django 2.2.1 on 2019-10-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0048_auto_20191017_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetapalete',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetapalete',
            name='impressora',
            field=models.CharField(blank=True, choices=[('Bobinadora_CAB_A4_200', 'BOBINADORA'), ('DM12_CAB_A4_200', 'DM12')], max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetapalete',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
    ]
