# Generated by Django 2.2.1 on 2019-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0049_auto_20191018_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetafinal',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='impressora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
    ]
