# Generated by Django 2.2.7 on 2019-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0051_auto_20191127_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='gsm',
            field=models.CharField(blank=True, choices=[('105', '105 gsm'), ('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm'), ('57', '57 gsm'), ('50', '50 gsm'), ('48', '48 gsm')], max_length=10, null=True, verbose_name='Gramagem'),
        ),
    ]
