# Generated by Django 2.2.7 on 2019-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0052_auto_20191202_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largura',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='gramagem',
            field=models.CharField(blank=True, choices=[('105', '105 gsm'), ('100', '100 gsm'), ('95', '95 gsm'), ('90', '90 gsm'), ('80', '80 gsm'), ('57', '57 gsm'), ('50', '50 gsm'), ('48', '48 gsm')], max_length=10, null=True, verbose_name='Gramagem'),
        ),
    ]
