# Generated by Django 2.2.7 on 2019-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0054_auto_20191204_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='largura_bobinagem',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura da bobinagem'),
        ),
    ]
