# Generated by Django 2.2.7 on 2019-12-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0055_auto_20191204_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['estado', '-data', '-eef'], 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='core_original',
            field=models.CharField(blank=True, choices=[('3', '3'), ('6', '6')], max_length=1, null=True, verbose_name='Core'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='largura_original',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura da bobinagem'),
        ),
        migrations.CreateModel(
            name='Nonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('designacao_fornecedor', models.CharField(max_length=200, unique=True, verbose_name='Designação do Fornecedor')),
                ('comp_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento total')),
                ('comp_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento actual')),
                ('largura', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('vazio', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Fornecedor', verbose_name='Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Nonwovens',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoNonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posicao', models.CharField(choices=[('SUP', 'Superior'), ('INF', 'Inferior')], max_length=10, verbose_name='Posição (Sup/Inf)')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('bobinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobinagem', verbose_name='Bobinagem')),
                ('nonwoven', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Nonwoven', verbose_name='Nonwoven')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Consumos de Nonwoven',
                'ordering': ['-timestamp'],
            },
        ),
    ]
