# Generated by Django 2.2.7 on 2019-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0055_auto_20191204_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='core_original',
            field=models.CharField(blank=True, choices=[('3', '3'), ('6', '6')], max_length=1, null=True, verbose_name='Core'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='largura_original',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura da bobinagem'),
        ),
    ]
