# Generated by Django 2.2.7 on 2019-12-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0056_auto_20191204_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('designacao', models.CharField(max_length=200, unique=True, verbose_name='Designação')),
                ('designacao_fornecedor', models.CharField(max_length=200, unique=True, verbose_name='Designação do Cliente')),
                ('fornecedor', models.CharField(max_length=200, unique=True, verbose_name='Fornecedor')),
                ('comp_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento total')),
                ('comp_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comprimento actual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Nonwovens',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['estado', '-data', '-eef'], 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.CreateModel(
            name='NwBobinagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posicao', models.CharField(choices=[('SUP', 'Superior'), ('INF', 'Inferior')], max_length=10, verbose_name='Posição (Sup/Inf)')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('bobinagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobinagem', verbose_name='Bobinagem')),
                ('nonwoven', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Nonwoven', verbose_name='Nonwoven')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Nonwoven-Bobinagens',
                'ordering': ['-timestamp'],
            },
        ),
    ]
