# Generated by Django 2.2.7 on 2019-12-06 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0057_auto_20191206_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NwBobinagem',
            new_name='Consumo',
        ),
        migrations.AlterModelOptions(
            name='consumo',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Consumos de Nonwoven'},
        ),
    ]
