# Generated by Django 2.2.7 on 2019-12-06 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0058_auto_20191206_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumo',
            new_name='ConsumoNonwoven',
        ),
    ]
