# Generated by Django 2.2.7 on 2019-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0059_auto_20191206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonwoven',
            name='largura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largura'),
        ),
    ]
