# Generated by Django 2.2.7 on 2019-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0060_nonwoven_largura'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonwoven',
            name='vazio',
            field=models.BooleanField(default=False, verbose_name='Utilizado'),
        ),
    ]
