# Generated by Django 2.2.7 on 2019-12-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0056_auto_20191209_1527'),
        ('producao', '0062_auto_20191209_1522'),
        ('producao', '0038_auto_20191209_1528'),
    ]

    operations = [
    ]
