# Generated by Django 2.2.7 on 2020-01-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0066_auto_20191213_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='largura',
            name='artigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Artigo', verbose_name='Artigo'),
        ),
        migrations.AddField(
            model_name='largura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Cliente', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='ArtigoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_client', models.CharField(max_length=200, unique=True, verbose_name='Cód. CLiente')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Artigo', verbose_name='Artigo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Cliente', verbose_name='Cliente')),
            ],
        ),
    ]
