# Generated by Django 2.2.7 on 2020-01-09 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0067_auto_20200109_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigocliente',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Artigos Cliente'},
        ),
        migrations.AddField(
            model_name='artigocliente',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artigocliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='artigocliente',
            name='cod_client',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Cód. Cliente'),
        ),
    ]
