# Generated by Django 2.2.7 on 2020-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0069_auto_20200121_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='order_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='etiquetafinal',
            name='order_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Order Number'),
        ),
    ]
