# Generated by Django 2.2.7 on 2020-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0070_auto_20200124_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='abv',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Abreviatura'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cod',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Fornecedor'),
        ),
        migrations.AlterField(
            model_name='etiquetafinal',
            name='order_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Order Number'),
        ),
    ]
