# Generated by Django 2.2.7 on 2020-01-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0071_auto_20200127_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rececao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rececao', models.CharField(max_length=20, unique=True, verbose_name='Receção')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Lotes')),
                ('estado', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada')], default='A', max_length=7, verbose_name='Estado da Receção')),
                ('encomenda', models.CharField(max_length=15, unique=True, verbose_name='Encomenda')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Fornecedor', verbose_name='Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
