# Generated by Django 2.2.7 on 2020-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0073_auto_20200129_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigonw',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Artigos Nonwoven'},
        ),
        migrations.AlterField(
            model_name='nonwoven',
            name='stack_num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Stack number'),
        ),
    ]
