# Generated by Django 2.2.7 on 2020-02-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0074_auto_20200131_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaNonwoven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cod_nw', models.CharField(max_length=100, verbose_name='Código NW')),
                ('nw_des', models.CharField(max_length=100, verbose_name='Descrição NW')),
                ('rececao_rec', models.CharField(max_length=100, verbose_name='Receção Rec')),
                ('encomenda', models.CharField(max_length=100, verbose_name='Encomenda')),
                ('data_rec', models.CharField(max_length=100, verbose_name='Data de Receção')),
                ('nonwoven', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Nonwoven', verbose_name='Nonwoven')),
                ('rececao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Rececao', verbose_name='Receção')),
            ],
            options={
                'verbose_name_plural': 'Etiquetas Nonwoven',
                'ordering': ['-timestamp'],
            },
        ),
    ]
