# Generated by Django 2.2.7 on 2020-02-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0075_etiquetanonwoven'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetanonwoven',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetanonwoven',
            name='impressora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetanonwoven',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
    ]
