# Generated by Django 2.2.7 on 2020-02-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0077_nonwoven_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetanonwoven',
            name='nonwoven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Nonwoven', verbose_name='Nonwoven'),
        ),
    ]
