# Generated by Django 2.2.7 on 2020-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0078_auto_20200207_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonwoven',
            name='descricao',
        ),
        migrations.AddField(
            model_name='nonwoven',
            name='cod_nw',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Nonwoven'),
        ),
    ]
