# Generated by Django 2.2.7 on 2020-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0079_auto_20200207_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='car',
            field=models.BooleanField(default=False, verbose_name='Carro andou para trás'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='fc',
            field=models.BooleanField(default=False, verbose_name='Falha de corte'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='fc_diam_fim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Falha de corte fim'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='fc_diam_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Falha de corte inicio'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='ff',
            field=models.BooleanField(default=False, verbose_name='Falha de filme'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='ff_m_fim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Falha de fimle fim'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='ff_m_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Falha de filme inicio'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='fmp',
            field=models.BooleanField(default=False, verbose_name='Falha de Matéria Prima'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='lac',
            field=models.BooleanField(default=False, verbose_name='Laçou'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='ncore',
            field=models.BooleanField(default=False, verbose_name='Não colou core/Falta de fita cola'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='prop',
            field=models.BooleanField(default=False, verbose_name='Propriedades'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='prop_obs',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Observações Propriedades'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='sbrt',
            field=models.BooleanField(default=False, verbose_name='Sobre tiragem'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='suj',
            field=models.BooleanField(default=False, verbose_name='Sujidade/Caiu do carro'),
        ),
    ]
