# Generated by Django 2.2.7 on 2020-03-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0081_auto_20200228_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentosBobines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('bobine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobine', verbose_name='Bobine')),
                ('palete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Palete', verbose_name='Palete')),
            ],
        ),
    ]
