# Generated by Django 2.2.7 on 2020-03-31 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0082_movimentosbobines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGranulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('produto_granulado', models.CharField(max_length=15, verbose_name='Produto Granulado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Produto Granulado',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimentosbobines',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Movimentos de Bobines'},
        ),
        migrations.AlterField(
            model_name='movimentosbobines',
            name='bobine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Bobine', verbose_name='Bobine'),
        ),
        migrations.AlterField(
            model_name='movimentosbobines',
            name='palete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.Palete', verbose_name='Palete'),
        ),
        migrations.AlterField(
            model_name='movimentosbobines',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Reciclado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lote', models.CharField(max_length=15, unique=True)),
                ('estado', models.CharField(choices=[('G', 'G'), ('R', 'R'), ('NOK', 'NOK')], default='G', max_length=4, verbose_name='Estado')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('obs', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('produto_granulado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.ProdutoGranulado', verbose_name='Produto Granulado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Reciclado',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lote', models.CharField(max_length=30, verbose_name='Lote')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('NOK', 'NOK')], default='Entrada', max_length=7, verbose_name='Tipo de movimento')),
                ('motivo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Movimentos de MP',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaReciclado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('lote', models.CharField(max_length=30, unique=True, verbose_name='Lote de Reciclado')),
                ('produto_granulado', models.CharField(max_length=10, verbose_name='Produto Granulado')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('reciclado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Reciclado', verbose_name='Reciclado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
