# Generated by Django 2.2.7 on 2020-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0084_auto_20200403_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='estado',
            field=models.CharField(choices=[('G', 'G'), ('DM', 'DM12'), ('R', 'R'), ('BA', 'BA'), ('LAB', 'LAB'), ('IND', 'IND'), ('HOLD', 'HOLD'), ('SC', 'SC')], default='LAB', max_length=4, verbose_name='Estado'),
        ),
    ]
