# Generated by Django 2.2.7 on 2020-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0090_auto_20200419_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclado',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
