# Generated by Django 2.2.7 on 2020-04-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0091_auto_20200419_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetareciclado',
            name='estado_impressao',
            field=models.BooleanField(default=False, verbose_name='Imprimir'),
        ),
        migrations.AddField(
            model_name='etiquetareciclado',
            name='impressora',
            field=models.CharField(blank=True, choices=[('Bobinadora_CAB_A4_200', 'BOBINADORA'), ('DM12_CAB_A4_200', 'DM12')], max_length=200, null=True, verbose_name='Impressora'),
        ),
        migrations.AddField(
            model_name='etiquetareciclado',
            name='num_copias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Cópias'),
        ),
        migrations.AlterField(
            model_name='reciclado',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='reciclado',
            name='timestamp_edit',
            field=models.DateTimeField(verbose_name='Edited'),
        ),
    ]
