# Generated by Django 2.2.7 on 2020-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0092_auto_20200419_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetareciclado',
            name='produto_granulado',
            field=models.CharField(max_length=20, verbose_name='Produto Granulado'),
        ),
    ]
