# Generated by Django 2.2.7 on 2020-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0093_auto_20200420_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetareciclado',
            name='impressora',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Impressora'),
        ),
    ]
