# Generated by Django 2.2.7 on 2020-04-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0095_auto_20200428_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetareciclado',
            name='timestamp',
        ),
    ]
