# Generated by Django 2.2.7 on 2020-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0096_remove_etiquetareciclado_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciclado',
            name='timestamp_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
