# Generated by Django 2.2.7 on 2020-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0097_reciclado_timestamp_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='data_expedicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expedição'),
        ),
        migrations.AddField(
            model_name='carga',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de expedição'),
        ),
        migrations.AddField(
            model_name='carga',
            name='expedida',
            field=models.BooleanField(default=False, verbose_name='Expedida'),
        ),
    ]
