# Generated by Django 2.2.7 on 2020-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0098_auto_20200429_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='hora_expedicao',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de expedição'),
        ),
    ]
