# Generated by Django 2.2.7 on 2020-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0101_auto_20200616_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='diam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diametro'),
        ),
    ]
