# Generated by Django 2.2.7 on 2020-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0106_auto_20200625_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='tipo_desp',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('BA', 'BA')], default=None, max_length=4, null=True, verbose_name='Tipo de desperdício'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='desp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desperdício'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='tipo_desp',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('BA', 'BA')], default=None, max_length=4, null=True, verbose_name='Tipo de desperdício'),
        ),
    ]
