# Generated by Django 2.2.7 on 2020-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0108_etiquetafinal_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetafinal',
            name='order_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Number'),
        ),
    ]
