# Generated by Django 2.2.7 on 2020-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0110_reciclado_tara'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='num_paletes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='num_paletes_actual',
            field=models.IntegerField(default=0),
        ),
    ]
