# Generated by Django 2.2.7 on 2020-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0111_auto_20200728_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista de Conclusão'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='num_paletes',
            field=models.IntegerField(default=0, verbose_name='Nº de Paletes Total'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='num_paletes_actual',
            field=models.IntegerField(default=0, verbose_name='Nº de Paletes Actual'),
        ),
    ]
