# Generated by Django 2.2.7 on 2020-07-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0112_auto_20200728_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='enc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Encomenda', verbose_name='Encomenda'),
        ),
    ]
