# Generated by Django 2.2.7 on 2020-07-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0009_auto_20200729_1812'),
        ('producao', '0113_palete_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planeamento.OrdemProducao', verbose_name='Ordem de Producao'),
        ),
    ]
