# Generated by Django 2.2.7 on 2020-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0115_remove_palete_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Adicionar Palete'),
        ),
    ]
