# Generated by Django 2.2.7 on 2020-08-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0116_palete_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palete',
            name='add',
        ),
    ]
