# Generated by Django 2.2.7 on 2020-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0118_palete_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='ordem_original',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ordem de produção Original'),
        ),
    ]
