# Generated by Django 2.2.7 on 2020-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0119_palete_ordem_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='ordem_original_stock',
            field=models.BooleanField(default=False, verbose_name='Ordem original Stock'),
        ),
    ]
