# Generated by Django 2.2.7 on 2020-09-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0121_auto_20200902_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='para_retrabalho',
            field=models.BooleanField(default=False, verbose_name='Para retrabalho'),
        ),
    ]
