# Generated by Django 2.2.7 on 2020-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0123_auto_20200918_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='num_palete_ordem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Palete Ordem'),
        ),
    ]
