# Generated by Django 2.2.7 on 2020-12-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0125_auto_20201203_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['-eef', 'estado', '-data'], 'verbose_name_plural': 'Encomendas'},
        ),
    ]
