# Generated by Django 2.2.7 on 2021-01-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0126_auto_20201207_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreLargura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.CharField(choices=[('3', '3'), ('6', '6')], max_length=1, verbose_name='Core')),
                ('largura', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso em Kg')),
            ],
        ),
    ]
