# Generated by Django 2.2.7 on 2021-01-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0127_corelargura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmbalamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Designação')),
                ('cartao', models.BooleanField(default=False, verbose_name='Cartão')),
                ('filme', models.BooleanField(default=False, verbose_name='Filme')),
                ('plastico', models.BooleanField(default=False, verbose_name='Plástico')),
                ('mdf', models.BooleanField(default=False, verbose_name='MDF')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso total')),
            ],
        ),
        migrations.AddField(
            model_name='palete',
            name='perfil_embalamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.PerfilEmbalamento', verbose_name='PerfilEmbalamento'),
        ),
    ]
