# Generated by Django 2.2.7 on 2021-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0129_auto_20210316_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhaencomenda',
            name='linha',
            field=models.IntegerField(default=0),
        ),
    ]
