# Generated by Django 2.2.7 on 2021-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0130_linhaencomenda_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data_encomenda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Encomenda'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='data_prevista_expedicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista de Expedição'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='data_solicitada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Solicitada de Expedição'),
        ),
        migrations.AlterField(
            model_name='linhaencomenda',
            name='prc',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Preço Metro'),
        ),
    ]
