# Generated by Django 2.2.7 on 2021-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0131_auto_20210317_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='prf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Proforma'),
        ),
    ]
