# Generated by Django 2.2.7 on 2021-04-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0133_auto_20210325_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. Cinta')),
                ('des', models.TextField(verbose_name='Descrição Cinta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. Core')),
                ('des', models.TextField(verbose_name='Descrição Core')),
                ('core', models.CharField(choices=[('3', '3'), ('6', '6')], max_length=1, verbose_name='Core')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Embalamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cinta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Cinta', verbose_name='Cinta')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Core', verbose_name='Core')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. Etiqueta')),
                ('des', models.TextField(verbose_name='Descrição Etiqueta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tipo', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.AddField(
            model_name='artigocliente',
            name='num_emendas_bobine',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de emendas por bobine'),
        ),
        migrations.CreateModel(
            name='TrasporteArtigoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('num_bobines_palete', models.PositiveIntegerField()),
                ('num_paletes_transporte', models.PositiveIntegerField()),
                ('artigocliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.ArtigoCliente', verbose_name='Artigo Cliente')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Transporte', verbose_name='Transporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('des', models.TextField(verbose_name='Tipo Emenda')),
                ('preta', models.BooleanField(default=False)),
                ('metalica', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='PaleteEmb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. Palete de embalamento')),
                ('des', models.TextField(verbose_name='Descrição Palete de Embalamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Mdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. MDF')),
                ('des', models.TextField(verbose_name='Descrição MDF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cod', models.CharField(max_length=200, verbose_name='Cód. Filme')),
                ('des', models.TextField(verbose_name='Descrição Filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaEmbalamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('qtd', models.PositiveIntegerField()),
                ('embalamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Embalamento', verbose_name='Username')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Etiqueta', verbose_name='Etiqueta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.AddField(
            model_name='embalamento',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Filme', verbose_name='Filme'),
        ),
        migrations.AddField(
            model_name='embalamento',
            name='mdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Mdf', verbose_name='MDF'),
        ),
        migrations.AddField(
            model_name='embalamento',
            name='paletemb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.PaleteEmb', verbose_name='Palete embalamento'),
        ),
        migrations.AddField(
            model_name='embalamento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='artigocliente',
            name='embalamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Embalamento', verbose_name='Embalamento'),
        ),
        migrations.AddField(
            model_name='artigocliente',
            name='tipoemenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.TipoEmenda', verbose_name='Tipo de Emenda'),
        ),
    ]
