# Generated by Django 2.2.7 on 2021-04-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0134_auto_20210409_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinta',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Descrição Cinta'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Descrição Etiqueta'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Descrição Filme'),
        ),
        migrations.AlterField(
            model_name='mdf',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Descrição MDF'),
        ),
        migrations.AlterField(
            model_name='paleteemb',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Descrição Palete de Embalamento'),
        ),
    ]
