# Generated by Django 2.2.7 on 2021-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0139_auto_20210602_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palete',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Peso bruto'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Peso liqudo'),
        ),
    ]
