# Generated by Django 2.2.7 on 2021-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0140_auto_20210604_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palete',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Peso bruto'),
        ),
        migrations.AlterField(
            model_name='palete',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Peso liqudo'),
        ),
    ]
