# Generated by Django 2.2.7 on 2020-07-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicastecnicas',
            options={'verbose_name_plural': 'Caracteristicas Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='ctinf',
            options={'verbose_name_plural': 'CTInfs'},
        ),
        migrations.AlterModelOptions(
            name='ctsup',
            options={'verbose_name_plural': 'CTSups'},
        ),
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'verbose_name_plural': 'Ordens de Produção'},
        ),
    ]
