# Generated by Django 2.2.7 on 2020-07-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0002_auto_20200729_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planeamento.CaracteristicasTecnicas', verbose_name='Caracteristicas Técnicas'),
        ),
    ]
