# Generated by Django 2.2.7 on 2020-07-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0003_auto_20200729_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='altura_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura máxima'),
        ),
    ]
