# Generated by Django 2.2.7 on 2020-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0004_auto_20200729_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='liminf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite Inferior'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='limsup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite Superior'),
        ),
    ]
