# Generated by Django 2.2.7 on 2020-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0005_auto_20200729_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='ativa',
            field=models.BooleanField(default=False, verbose_name='Em progresso'),
        ),
    ]
