# Generated by Django 2.2.7 on 2020-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0006_ordemproducao_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='completa',
            field=models.BooleanField(default=False, verbose_name='Completa'),
        ),
    ]
