# Generated by Django 2.2.7 on 2020-07-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0008_auto_20200729_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'verbose_name_plural': 'Ordens de Produção'},
        ),
    ]
