# Generated by Django 2.2.7 on 2020-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0009_auto_20200729_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='num_paletes_produzidas',
            field=models.IntegerField(default=0, verbose_name='Nº de paletes produzidas'),
        ),
    ]
