# Generated by Django 2.2.7 on 2020-08-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0010_ordemproducao_num_paletes_produzidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='enc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Encomenda', verbose_name='Encomenda'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='enrolamento',
            field=models.CharField(default='Anti-horario', max_length=100, verbose_name='Sentido do enrolamento'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='etiqueta_bobine',
            field=models.IntegerField(default=2, verbose_name='Etiqueta por bobine'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='etiqueta_palete',
            field=models.IntegerField(default=4, verbose_name='Etiqueta por palete'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='freq_amos',
            field=models.IntegerField(default=4, verbose_name='Frequência de amostragem por bobinagem'),
        ),
    ]
