# Generated by Django 2.2.7 on 2020-08-05 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0011_auto_20200805_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_prevista_fim',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Prevista de Fim'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_prevista_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Prevista de Início'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inico'),
        ),
    ]
