# Generated by Django 2.2.7 on 2020-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0013_ordemproducao_num_paletes_stock_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='tipo_emenda',
            field=models.CharField(choices=[('Fita Preta', 'Fita Preta'), ('Fita metálica', 'Fita metálica')], default='Fita Preta', max_length=200, verbose_name='Tipo de Emenda'),
        ),
    ]
