# Generated by Django 2.2.7 on 2020-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0014_ordemproducao_tipo_emenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='retrabalho',
            field=models.BooleanField(default=False, verbose_name='Ordem de retrabalho'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='enrolamento',
            field=models.CharField(choices=[('Anti-horário', 'Anti-horário'), ('Horário', 'Horário')], default='Anti-horario', max_length=100, verbose_name='Sentido do enrolamento'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_transporte',
            field=models.CharField(choices=[('---', '---'), ('Camião', 'Camião'), ('Contentor', 'Contentor')], default='---', max_length=20, verbose_name='Tipo de Transporte'),
        ),
    ]
