# Generated by Django 2.2.7 on 2020-09-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0121_auto_20200902_1049'),
        ('planeamento', '0015_auto_20200902_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='nwinf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='nwsup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nonwoven Superior'),
        ),
    ]
