# Generated by Django 2.2.7 on 2020-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0016_auto_20200908_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='coa_aprov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coa de Aprovação'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='ficha_processo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ficha de Processo'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='limite_con',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Limite Cónico'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='limite_desc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Limite Descentrado'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='paletes_camiao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Paletes por camião'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_transporte',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Camião', 'Camião'), ('Contentor', 'Contentor')], default='---', max_length=20, null=True, verbose_name='Tipo de Transporte'),
        ),
    ]
