# Generated by Django 2.2.7 on 2020-09-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0122_bobine_para_retrabalho'),
        ('planeamento', '0019_auto_20200908_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobinesARetrabalhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.Bobine', verbose_name='Bobine')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeamento.OrdemProducao', verbose_name='Ordem de Produção')),
            ],
        ),
    ]
