# Generated by Django 2.2.7 on 2020-09-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0020_bobinesaretrabalhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinesaretrabalhar',
            name='retrabalhar',
            field=models.BooleanField(default=True, verbose_name='Retrabalhar'),
        ),
    ]
