# Generated by Django 2.2.7 on 2020-09-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0021_bobinesaretrabalhar_retrabalhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='ficha_técnica',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/tecnic/'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='of',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/of/'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='base',
            field=models.CharField(choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, verbose_name='Base'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='core',
            field=models.CharField(choices=[('3"', '3"'), ('6"', '6"')], max_length=2, verbose_name='Core'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_prevista_fim',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data Prevista de Fim'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='embal',
            field=models.CharField(choices=[('Filme Estirável', 'Filme Estirável')], max_length=50, verbose_name='Embalamento'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='ficha_processo',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/process/'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='nwinf',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP')], max_length=200, null=True, verbose_name='Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='nwsup',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP')], max_length=200, null=True, verbose_name='Nonwoven Superior'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_emenda',
            field=models.CharField(blank=True, choices=[('Fita Preta', 'Fita Preta'), ('Fita metálica', 'Fita metálica'), ('Fita metálica e Fita Preta', 'Fita metálica e Fita Preta')], default='Fita Preta', max_length=200, null=True, verbose_name='Tipo de Emenda'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_transporte',
            field=models.CharField(blank=True, choices=[('Camião', 'Camião'), ('Contentor', 'Contentor')], default='---', max_length=20, null=True, verbose_name='Tipo de Transporte'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='topo',
            field=models.CharField(choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, verbose_name='Topo'),
        ),
    ]
