# Generated by Django 2.2.7 on 2020-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0022_auto_20200917_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemproducao',
            old_name='ficha_técnica',
            new_name='ficha_tecnica',
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='base',
            field=models.CharField(blank=True, choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, null=True, verbose_name='Base'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='coa_aprov',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/coa/'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='embal',
            field=models.CharField(blank=True, choices=[('Filme Estirável', 'Filme Estirável')], max_length=50, null=True, verbose_name='Embalamento'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_transporte',
            field=models.CharField(blank=True, choices=[('Camião', 'Camião'), ('Contentor', 'Contentor')], max_length=20, null=True, verbose_name='Tipo de Transporte'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='topo',
            field=models.CharField(blank=True, choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, null=True, verbose_name='Topo'),
        ),
    ]
