# Generated by Django 2.2.7 on 2020-09-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0023_auto_20200918_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='tipo_paletes',
            field=models.CharField(choices=[('970x970', '970x970')], default='970x970', max_length=200, verbose_name='Tipo de Paletes'),
        ),
    ]
