# Generated by Django 2.2.7 on 2020-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0025_auto_20200918_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='hora_prevista_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora prevista de fim'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fim'),
        ),
    ]
