# Generated by Django 2.2.7 on 2020-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0026_auto_20200918_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='altura_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Altura máxima'),
        ),
    ]
