# Generated by Django 2.2.7 on 2020-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0027_auto_20200930_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='bobines_por_palete_inf',
            field=models.IntegerField(default=0, verbose_name='Bobines por Palete Inferior'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='bobines_por_palete',
            field=models.IntegerField(default=0, verbose_name='Bobines por Palete Superior ou Única'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='hora_prevista_inicio',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='Hora prevista de inicio'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='palete_por_palete',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Palete por Palete'),
        ),
    ]
