# Generated by Django 2.2.7 on 2020-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0028_auto_20201015_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='pack_list',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/packlist/'),
        ),
    ]
