# Generated by Django 2.2.7 on 2021-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0030_auto_20210316_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='ori_qua',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/oriqualidade/'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='res_prod',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/resumoproducao/'),
        ),
    ]
